name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust ${{ matrix.rust_version }} (${{ matrix.package }} - ${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rust_version: [stable]
        package: [runtime_injector, runtime_injector_actix]
        features: [arc, rc]
        exclude:
          - package: runtime_injector_actix
            features: rc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Check formatting
        run: >-
          cargo fmt
          --
          --check
      - name: Run tests
        run: >-
          cargo test
          -p ${{ matrix.package }}
          --verbose
          --no-default-features
          --features ${{ matrix.features }}

  clippy:
    name: Clippy (${{ matrix.package }} - ${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [runtime_injector, runtime_injector_actix]
        features: [arc, rc]
        exclude:
          - package: runtime_injector_actix
            features: rc
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: >-
          cargo clippy
          -p ${{ matrix.package }}
          --tests
          --no-default-features
          --features ${{ matrix.features }}
